### PR TITLE
VKC-122: Move internal registry to projects-stg

### PR DESCRIPTION
**Pull request by arunmk**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- 

## Checklist
- [X] tested locally
- [X] updated any relevant dependencies
- [X] updated any relevant documentation or examples

## Testing Done
Did a make and then a docker pull

## Issue
N/A

Fixes #
N/A

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/187)

### CODE REVIEW

**Review by lzichong — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/187)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk and @ymo24)

___
*[`manifests/vcloud-csi-config.yaml.bak` line 2 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/187#-NVelsFV1RwdAfQOwYc6:-NVelsFV1RwdAfQOwYc7:b1ybjhc) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/c69f8d4c66729eb0e5413c8f7618ee3ef3426a9d/manifests/vcloud-csi-config.yaml.bak#L2)):*
> ```
> ---
> apiVersion: v1
> ```

Was this file meant to be included as well?

**Review by ymo24 — COMMENTED** [review]
:lgtm:  after addressing the comments: vcloud-csi-config.yaml.bak should not be here

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/187#-:-NVeneKk1BzfRUKWysGh:bvbndz2)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk)

**Review by arunmk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/187)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @lzichong)

___
*[`manifests/vcloud-csi-config.yaml.bak` line 2 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/187#-NVelsFV1RwdAfQOwYc6:-NVesD-m8gcHfM3H_7fd:b-9l1mqc) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/c69f8d4c66729eb0e5413c8f7618ee3ef3426a9d/manifests/vcloud-csi-config.yaml.bak#L2)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Was this file meant to be included as well?
</blockquote></details>

Fixed, thanks @lzichong

**Review by lzichong — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/187)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @arunmk)

**Comment by arunmk** [comment]
Removed, thanks @ymo24

**Review by ymo24 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/187#-:-NVfsnQWC9smeBwqBgUM:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @lzichong)

**Pull request merged**
