### PR TITLE
fix the unit test failing issue #VCDA 3546

### PR DESCRIPTION
**Pull request by ymo24**
Ticket: VCDA-3546

* Fix an issue with library imports during CSI unit testing.
* Pass two unit test **TestDiskCreateAttach** and **TestRdeEtag** on personal cluster.
* Configuration file is kept for further use.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42)

### CODE REVIEW

**Review by arunmk — CHANGES_REQUESTED** [review]
Have asked for a set of removals. I am not certain things will work after that, but I think they should. Could you please try and let me know if there are issues.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-:-MzxUiJB2ztoZoY65Pmc:b8bqnxo)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @arunmk and @ymo24)

___
*[pkg/vcdcsiclient/common_system_test.go, line 28 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-MzxTVaj441iGPq_D25t:-MzxTVaj441iGPq_D25u:brevop3) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/15a703d3727352d1a1a49cec0573080a0a199ff0/pkg/vcdcsiclient/common_system_test.go#L28)):*
> ```Go
> }
> 
> // Ports :
> ```

We can remove structs `Ports`, `OneArm`, `LBConfig`
___
*[pkg/vcdcsiclient/common_system_test.go, line 63 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-MzxThYG8g9J-U0mSXFg:-MzxThYG8g9J-U0mSXFh:bccnpku) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/15a703d3727352d1a1a49cec0573080a0a199ff0/pkg/vcdcsiclient/common_system_test.go#L63)):*
> ```Go
> }
> 
> func getOneArmValStrict(val interface{}, defaultVal *vcdclient.OneArm) *vcdclient.OneArm {
> ```

This function can be removed
___
*[pkg/vcdcsiclient/common_system_test.go, line 71 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-MzxTkWICtdTZVfjAA41:-MzxTkWICtdTZVfjAA42:bidnym4) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/15a703d3727352d1a1a49cec0573080a0a199ff0/pkg/vcdcsiclient/common_system_test.go#L71)):*
> ```Go
> }
> 
> func getInt32ValStrict(val interface{}, defaultVal int32) int32 {
> ```

This function also can be removed I think
___
*[pkg/vcdcsiclient/common_system_test.go, line 94 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-MzxToNq8OQx4dMQvDEP:-MzxToNq8OQx4dMQvDEQ:b-l6mwxj) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/15a703d3727352d1a1a49cec0573080a0a199ff0/pkg/vcdcsiclient/common_system_test.go#L94)):*
> ```Go
> 
> 	insecure := true
> 	oneArm := &vcdclient.OneArm{
> ```

remove
___
*[pkg/vcdcsiclient/common_system_test.go, line 107 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-MzxTsMu7lFDkrXDDeR6:-MzxTsMu7lFDkrXDDeR7:bbrqvg4) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/15a703d3727352d1a1a49cec0573080a0a199ff0/pkg/vcdcsiclient/common_system_test.go#L107)):*
> ```Go
> 			case "org":
> 				cloudConfig.VCD.Org = getStrValStrict(val, cloudConfig.VCD.Org)
> 			case "network":
> ```

I think the following cases can be removed: `network`, `subnet`, `oneArm`, `httpPort`, `httpsPort`, `certAlias`
___
*[pkg/vcdcsiclient/common_system_test.go, line 137 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-MzxU3fF0YKbgATixlEH:-MzxU3fF0YKbgATixlEI:bjm0fx8) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/15a703d3727352d1a1a49cec0573080a0a199ff0/pkg/vcdcsiclient/common_system_test.go#L137)):*
> ```Go
> 	}
> 
> 	return vcdclient.NewVCDClientFromSecrets(
> ```

The above removed params can be passed as "", nil or 0 here.
___
*[pkg/vcdcsiclient/disks_system_test.go, line 79 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-MzxUHcO62zEK0SgiWSs:-MzxUHcO62zEK0SgiWSt:bygn3ey) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/15a703d3727352d1a1a49cec0573080a0a199ff0/pkg/vcdcsiclient/disks_system_test.go#L79)):*
> ```Go
> 	// get VM
> 	//nodeID := "vm1"
> 	nodeID := "mstr-eb9x"
> ```

Can you remove the previous commented out line, and also add a comment saying that this needs to be the name of an existing VM
___
*[vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/config/vcloud-ccm-config.yaml, line 7 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-MzxUVNV5JybMbDv1HfQ:-MzxUVNV5JybMbDv1HfR:b-bfd1qc) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/15a703d3727352d1a1a49cec0573080a0a199ff0/vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/config/vcloud-ccm-config.yaml#L7)):*
> ```YAML
>   user: "vmware-cloud-director-user"
>   secret: "password-of-vmware-cloud-director-user"
>   network: "network-used-in-org-vdc"
> ```

remove the following fields here: `network`, `vipSubnet`, `loadbalancer`(section including `oneArm` and `ports`), `certAlias`

**Review by ymo24 — COMMENTED** [review]
> Dismissed @arunmk from a discussion.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42)* status: 0 of 6 files reviewed, 7 unresolved discussions (waiting on @arunmk)

___
*[pkg/vcdcsiclient/common_system_test.go, line 28 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-MzxTVaj441iGPq_D25t:-Mzzln2ZCJz7rl9LEcCO:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/15a703d3727352d1a1a49cec0573080a0a199ff0/pkg/vcdcsiclient/common_system_test.go#L28)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

We can remove structs `Ports`, `OneArm`, `LBConfig`
</blockquote></details>

Done.
___
*[pkg/vcdcsiclient/common_system_test.go, line 63 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-MzxThYG8g9J-U0mSXFg:-MzzlohB6nL4hAhyo_1b:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/15a703d3727352d1a1a49cec0573080a0a199ff0/pkg/vcdcsiclient/common_system_test.go#L63)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This function can be removed
</blockquote></details>

Done.
___
*[pkg/vcdcsiclient/common_system_test.go, line 71 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-MzxTkWICtdTZVfjAA41:-MzzlpbmAHXngUFevVcF:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/15a703d3727352d1a1a49cec0573080a0a199ff0/pkg/vcdcsiclient/common_system_test.go#L71)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This function also can be removed I think
</blockquote></details>

Done.
___
*[pkg/vcdcsiclient/common_system_test.go, line 94 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-MzxToNq8OQx4dMQvDEP:-Mzzlq8_4dXiB5Fu5VSU:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/15a703d3727352d1a1a49cec0573080a0a199ff0/pkg/vcdcsiclient/common_system_test.go#L94)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[pkg/vcdcsiclient/common_system_test.go, line 107 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-MzxTsMu7lFDkrXDDeR6:-Mzzlqcz92PBQUX-AC-O:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/15a703d3727352d1a1a49cec0573080a0a199ff0/pkg/vcdcsiclient/common_system_test.go#L107)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

I think the following cases can be removed: `network`, `subnet`, `oneArm`, `httpPort`, `httpsPort`, `certAlias`
</blockquote></details>

Done.
___
*[pkg/vcdcsiclient/common_system_test.go, line 137 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-MzxU3fF0YKbgATixlEH:-Mzzls9gDofXzq3rt1XD:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/15a703d3727352d1a1a49cec0573080a0a199ff0/pkg/vcdcsiclient/common_system_test.go#L137)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

The above removed params can be passed as "", nil or 0 here.
</blockquote></details>

Done.
___
*[pkg/vcdcsiclient/disks_system_test.go, line 79 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-MzxUHcO62zEK0SgiWSs:-Mzzlt8OBb9fL79sLdny:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/15a703d3727352d1a1a49cec0573080a0a199ff0/pkg/vcdcsiclient/disks_system_test.go#L79)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can you remove the previous commented out line, and also add a comment saying that this needs to be the name of an existing VM
</blockquote></details>

Done.
___
*[vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/config/vcloud-ccm-config.yaml, line 7 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-MzxUVNV5JybMbDv1HfQ:-MzzlRtC6B5epGoXgnDl:bmxap4) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/15a703d3727352d1a1a49cec0573080a0a199ff0/vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/config/vcloud-ccm-config.yaml#L7)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

remove the following fields here: `network`, `vipSubnet`, `loadbalancer`(section including `oneArm` and `ports`), `certAlias` 
</blockquote></details>


good

**Review by arunmk — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-:-N-5304tCqOmhkP2K-zT:bnfp4nl)* status: 0 of 6 files reviewed, 7 unresolved discussions (waiting on @arunmk)

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42)* status: all files reviewed, 8 unresolved discussions (waiting on @arunmk and @ymo24)

___
*[pkg/vcdcsiclient/disks_system_test.go, line 29 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/42#-N-BZ9bKBYWp_9-zwNz4:-N-BZ9bKBYWp_9-zwNz5:b7z797e) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/5137febf3501c051ac8b50edf3333bec7ecf0ff6/pkg/vcdcsiclient/disks_system_test.go#L29)):*
> ```Go
> func TestDiskCreateAttach(t *testing.T) {
> 
> 	vcdcsiclient := new(Client)
> ```

nit: this would be more readable as `vcdCsiClient` and when used elsewhere

**Pull request merged**
