### PR TITLE
[VCDA-3465] Update RDE.status.CSI.PersistentVolumes for RDE 1.1.0 version

### PR DESCRIPTION
**Pull request by ymo24**
* Created RDE.status.CSI.PersistentVolumes.
* Testing done: 
1. Replaced the docker image in CSI pods -> Created new PV in K8S -> Check the RDE CSI Section.
2. Passed the unit test (create disk and attach to VM)

Signed-off-by: ymo24 <ymo@vmware.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/50)

### CODE REVIEW

**Comment by Anirudh9794** [comment]
*[`pkg/util/defined_entity_util.go` line 97 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/50#-N1QJPtSC7QaMN_Y_S_q:-N1QJPtSC7QaMN_Y_S_r:b9r8cef) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/fbe81c89753323c28059989cecc6623c1020c3cf/pkg/util/defined_entity_util.go#L97)):*
> ```Go
> 		csiEntry, ok := statusMap["csi"]
> 		if !ok {
> 			return nil, fmt.Errorf("could not find 'csi' entry in defined entity")
> ```

Instead of erroring out if CSI section is absent, can we create an empty section and add the updatedPVs?

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/50)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[`pkg/util/defined_entity_util.go` line 97 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/50#-N1QJPtSC7QaMN_Y_S_q:-N1QK1rYEZxbcqN0H4Wq:bgy3d5r) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/fbe81c89753323c28059989cecc6623c1020c3cf/pkg/util/defined_entity_util.go#L97)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Instead of erroring out if CSI section is absent, can we create an empty section and add the updatedPVs?
</blockquote></details>

Can we create an empty section directly? I thought if we get error here, the CSI section must failed the RDE resolve.

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: some minor comments

> Reviewed 2 of 144 files at r2, 6 of 6 files at r4, 2 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/50#-:-N1pa1Nn0QkPSn933LjV:bk5azfg)* status: 10 of 146 files reviewed, 4 unresolved discussions (waiting on @arunmk, @ltimothy7, and @ymo24)

___
*[`pkg/config/cloudconfig.go` line 41 at r5](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/50#-N1pYNlcEXPVWuXLmFK8:-N1pYNlcEXPVWuXLmFK9:bnn5lt2) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/891dc678708cb8eb275506a84ce9480798e865db/pkg/config/cloudconfig.go#L41)):*
> ```Go
> }
> 
> func GetUserAndOrg(fullUserName string, clusterOrg string, currentUserOrg string) (userOrg string, userName string, err error) {
> ```

Can you remove this method and use the GetUserAndOrg() in vcdsdk?
___
*[`pkg/csi/controller.go` line 49 at r5](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/50#-N1p_T3jBX6Q1l_tDZhx:-N1p_T3jBX6Q1l_tDZhy:bp6tm7h) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/891dc678708cb8eb275506a84ce9480798e865db/pkg/csi/controller.go#L49)):*
> ```Go
> )
> 
> type controllerServer struct {
> ```

can we define the structure as 
```
type controllerServer struct {
	Driver       *VCDDriver
	DiskManager *vcdcsiclient.DiskManager
        ClusterID string
        VAppName string
}

```
and remove ClusterID and VAppName from DiskManager if ClusterID and VAppName are not used within DiskManager?
___
*[`pkg/util/defined_entity_util.go` line 97 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/50#-N1QJPtSC7QaMN_Y_S_q:-N1pZ5o22P3fdWpJYgjk:bftwfpi) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/fbe81c89753323c28059989cecc6623c1020c3cf/pkg/util/defined_entity_util.go#L97)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

Can we create an empty section directly? I thought if we get error here, the CSI section must failed the RDE resolve.
</blockquote></details>

I think it is okay to create an empty section here because ultimately we want an RDE with csi section populated with the correct values.
___
*[`pkg/util/defined_entity_util.go` line 99 at r5](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/50#-N1pZQP8DYQXihjaBz7L:-N1pZQP8DYQXihjaBz7M:bkl7pl0) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/891dc678708cb8eb275506a84ce9480798e865db/pkg/util/defined_entity_util.go#L99)):*
> ```Go
> 			newCsiMap := make(map[string]interface{})
> 			newCsiMap["persistentVolumes"] = updatedPvs
> 			statusMap["csi"] = newCsiMap
> ```

I think newCsiMap["name"] and newCsiMap["version"] can also be populated.

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/50)* status: 10 of 146 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @ltimothy7)

___
*[`pkg/config/cloudconfig.go` line 41 at r5](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/50#-N1pYNlcEXPVWuXLmFK8:-N1paqVMDNS7-FxM2S_E:b-iry7x8) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/891dc678708cb8eb275506a84ce9480798e865db/pkg/config/cloudconfig.go#L41)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Can you remove this method and use the GetUserAndOrg() in vcdsdk?
</blockquote></details>

Done, thanks
___
*[`pkg/csi/controller.go` line 49 at r5](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/50#-N1p_T3jBX6Q1l_tDZhx:-N1qe7_0ErHEfsl7pS0N:blxi5nc) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/891dc678708cb8eb275506a84ce9480798e865db/pkg/csi/controller.go#L49)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

can we define the structure as 
```
type controllerServer struct {
	Driver       *VCDDriver
	DiskManager *vcdcsiclient.DiskManager
        ClusterID string
        VAppName string
}

```
and remove ClusterID and VAppName from DiskManager if ClusterID and VAppName are not used within DiskManager?
</blockquote></details>

The following struct would be applied after discussion. Thank you Aniruddha.



_Code snippet:_
```Go
type controllerServer struct {
	Driver      *VCDDriver
	DiskManager *vcdcsiclient.DiskManager
	VAppName    string
}    
```
___
*[`pkg/util/defined_entity_util.go` line 97 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/50#-N1QJPtSC7QaMN_Y_S_q:-N1qeEHz3Jb-pBDv4Zxz:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/fbe81c89753323c28059989cecc6623c1020c3cf/pkg/util/defined_entity_util.go#L97)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think it is okay to create an empty section here because ultimately we want an RDE with csi section populated with the correct values.
</blockquote></details>

Done.
___
*[`pkg/util/defined_entity_util.go` line 99 at r5](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/50#-N1pZQP8DYQXihjaBz7L:-N1paziJ-9E_h8YBgQo8:b-iry7x8) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/891dc678708cb8eb275506a84ce9480798e865db/pkg/util/defined_entity_util.go#L99)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think newCsiMap["name"] and newCsiMap["version"] can also be populated. 
</blockquote></details>

Done, thanks

**Pull request closed without merging**
