### PR TITLE
[VCDA-5534] update makefile

### PR DESCRIPTION
**Pull request by abaruni**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- 

## Checklist
- [ ] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## Testing Done
Please provide a screenshot of the testing results for the code change in this Pull Request. Verify that this pull request's code change will not affect CSI's normal operation

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/194)

### CODE REVIEW

**Review by arunmk — APPROVED** [review]
:lgtm:
I assume that the removal of git sha is based on the earlier discussion where we get a different sort of tag for the images.

> Reviewed 5 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/194#-:-NYeqhxn1O5yA5YQ8Llu:b-n1lbu6)* status: 5 of 18 files reviewed, 1 unresolved discussion (waiting on @abaruni, @lzichong, and @rocknes)

___
*[`go.mod` line 30 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/194#-NYemvHD-4hh7cu7DR5u:-NYemvHD-4hh7cu7DR5v:b58ucn7) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/42676e3e96411d6d7ee1d118564272ca84aa3fd9/go.mod#L30)):*
> ```XML
> 	k8s.io/api v0.22.1
> 	k8s.io/apimachinery v0.22.1
> 	k8s.io/client-go v0.22.1
> ```

Does this need OSL to be respun by Aashima?

**Review by abaruni — COMMENTED** [review]
just here. where we are actually building them, the sha is part of the image version tag. the version can also be passed into the make command

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/194#-:-NYx7ZA7Cz6Rm5rawBtG:be9ef3j)* status: 5 of 18 files reviewed, 1 unresolved discussion (waiting on @lzichong and @rocknes)

**Review by rocknes — APPROVED** [review]
> Reviewed 16 of 18 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/194)* status: all files reviewed, 2 unresolved discussions (waiting on @abaruni, @arunmk, and @lzichong)

___
*[`Dockerfile` line 13 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/194#-NYyA3_M2Q9OMT-yNBWl:-NYyA3_M2Q9OMT-yNBWm:b8t3d9n) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/485d3127024804ac11a0b84b678cee34b7e2e263/Dockerfile#L13)):*
> ```Dockerfile
> 
> ENV GOPATH /go
> RUN make build-within-docker && \
> ```

The build within docker script pattern was deployed to avoid building the container images on dev machines with different configurations. I guess we will make it mandatory to build images henceforth only via the build pipeline.
___
*[`manifests/csi-controller.yaml` line 143 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/194#-NYyBKSnEM6l0JhW2R9k:-NYyBKSnEM6l0JhW2R9l:bfln4mu) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/485d3127024804ac11a0b84b678cee34b7e2e263/manifests/csi-controller.yaml#L143)):*
> ```YAML
>               add: ["SYS_ADMIN"]
>             allowPrivilegeEscalation: true
>           image: projects-stg.registry.vmware.com/vmware-cloud-director/cloud-director-named-disk-csi-driver:main-branch.946348b
> ```

@arunmk should this be main-branch or should we change it to something like 1.4.0?

**Review by abaruni — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/194)* status: all files reviewed, 2 unresolved discussions (waiting on @arunmk and @lzichong)

___
*[`Dockerfile` line 13 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/194#-NYyA3_M2Q9OMT-yNBWl:-NYzPN6f9STOrgb1Z8l8:b-2wm7mp) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/485d3127024804ac11a0b84b678cee34b7e2e263/Dockerfile#L13)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

The build within docker script pattern was deployed to avoid building the container images on dev machines with different configurations. I guess we will make it mandatory to build images henceforth only via the build pipeline.
</blockquote></details>

yep. but that has been unsuccessful on the build machines. also we are explicitly telling the go compiler for which platform and architecture to compile it, so it really doesn't matter where it is compiled

**Review by lzichong — APPROVED** [review]
:lgtm: after addressing comments

> Reviewed 17 of 18 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/194#-:-NZ-ALBHBe_sN6NjzuFV:b-98fkod)* status: all files reviewed, 4 unresolved discussions (waiting on @abaruni and @arunmk)

___
*[`Makefile` line 166 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/194#-NZ-9YABChAT-VeAdYVO:-NZ-9YABChAT-VeAdYVP:bxw4vqd) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/e9199b03a5af87e239ec670c44a6db6841fb1ea8/Makefile#L166)):*
> ```Makefile
> 
> .PHONY: docker-push-csi
> docker-push-cpi: # Push CSI image to registry.
> ```

I think this should be `docker-push-csi`
___
*[`Makefile` line 180 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/194#-NZ-9cS55aGd0nHgNXGX:-NZ-9cS55aGd0nHgNXGY:bv99ui1) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/e9199b03a5af87e239ec670c44a6db6841fb1ea8/Makefile#L180)):*
> ```Makefile
> 
> .PHONY: docker-push
> docker-push: docker-push-cpi docker-push-artifacts docker-push-gcr-csi ## Push images to container registry.
> ```

I think `docker-push-cpi` here should be `docker-push-csi` as well

**Review by abaruni — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/194)* status: 17 of 18 files reviewed, 4 unresolved discussions (waiting on @arunmk, @lzichong, and @rocknes)

___
*[`Makefile` line 166 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/194#-NZ-9YABChAT-VeAdYVO:-NZBicm29tp_nbgsmFsi:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/e9199b03a5af87e239ec670c44a6db6841fb1ea8/Makefile#L166)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

I think this should be `docker-push-csi`
</blockquote></details>

Done.
___
*[`Makefile` line 180 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/194#-NZ-9cS55aGd0nHgNXGX:-NZBidV_7uaAW57zg_F1:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/e9199b03a5af87e239ec670c44a6db6841fb1ea8/Makefile#L180)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

I think `docker-push-cpi` here should be `docker-push-csi` as well
</blockquote></details>

Done.

**Pull request merged**
