### PR TITLE
VKC-213: Fix non-AZ clusters

### PR DESCRIPTION
**Pull request by arunmk**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- There were some places where the VDC __object__ was sent as nil, and there were a few places where the zone object was checked, but it could have zero zones. That caused the disk to not be created. This change fixed that.
- There is another cleanup where I reorganized a small function. I moved from an object being passed to  VDC name being passed.

## Checklist
- [X] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## Testing Done
Please provide a screenshot of the testing results for the code change in this Pull Request. Verify that this pull request's code change will not affect CSI's normal operation

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/272)

### CODE REVIEW

**Review by ymo24 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/272)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @abaruni and @lzichong)

**Review by lzichong — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/272)* status: all files reviewed, 1 unresolved discussion (waiting on @abaruni and @arunmk)

___
*[`pkg/vcdcsiclient/disks.go` line 352 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/272#-NvJLeKgAa45kk9dVuzE:-NvJLeKgAa45kk9dVuzF:b-oxrwd4) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/70b4f205f8330551bee3c00622db3b7616ce53e2/pkg/vcdcsiclient/disks.go#L352)):*
> ```Go
> 
> 	if zm == nil && len(zm.VdcToZoneMap) == 0 {
> 		for ovdcName, zone := range zm.VdcToZoneMap {
> ```

Since len(zm.VdcToZoneMap) == 0, we shouldn't be entering this loop right?

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/272)* status: all files reviewed, 1 unresolved discussion (waiting on @abaruni and @arunmk)

___
*[`pkg/vcdcsiclient/disks.go` line 352 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/272#-NvJLeKgAa45kk9dVuzE:-NvJLugP7scJ7AzwIFSO:b-2uvqpj) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/70b4f205f8330551bee3c00622db3b7616ce53e2/pkg/vcdcsiclient/disks.go#L352)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Since len(zm.VdcToZoneMap) == 0, we shouldn't be entering this loop right?
</blockquote></details>

Should this logic be inverted to zm != nil && len != 0?

**Review by lzichong — APPROVED** [review]
:lgtm: after addressing comment

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/272#-:-NvJMJDO9O33H0tWOwjk:bkbnwf4)* status: all files reviewed, 1 unresolved discussion (waiting on @abaruni and @arunmk)

**Review by lzichong — APPROVED** [review]
:lgtm: after the latest changes

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/272#-:-NvJRHaZB2Ece-fp2SpW:b-sruyok)* status: all files reviewed, 1 unresolved discussion (waiting on @abaruni and @arunmk)

**Pull request merged**
