### PR TITLE
[VCDA-5806] Ensure airgapped container tags are same as binary image tags

### PR DESCRIPTION
**Pull request by lzichong**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- Updates the tagging of airgapped artifacts to `$version.$gitSha`

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## Testing Done
Please provide a screenshot of the testing results for the code change in this Pull Request. Verify that this pull request's code change will not affect CSI's normal operation

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/193)

### CODE REVIEW

**Review by arunmk — APPROVED** [review]
:lgtm: with a small change needed

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/193#-:-NWyGPMr0BkvlByI5EMn:bwb2i5e)* status: all files reviewed, 1 unresolved discussion (waiting on @abaruni, @lzichong, and @rocknes)

___
*[`Makefile` line 44 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/193#-NWyGILKDfLdjJdztFn3:-NWyGILKDfLdjJdztFn4:b-mfx1wh) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/a8236db87806eeeaf5c566eecfa29e70971429cf/Makefile#L44)):*
> ```Makefile
> 	sed -e "s/__GIT_COMMIT__/$(GITCOMMIT)/g" -e "s/__VERSION__/$(version)/g" artifacts/default-csi-node-crs-airgap.yaml.template > artifacts/csi-node-crs-airgap.yaml.template
> 	sed -e "s/__GIT_COMMIT__/$(GITCOMMIT)/g" -e "s/__VERSION__/$(version)/g" -e "s~__REGISTRY__~$(REGISTRY)~g" artifacts/bom.json.template > artifacts/bom.json
> 	sed -e "s/__GIT_COMMIT__/$(GITCOMMIT)/g" -e "s/__VERSION__/$(version)/g" -e "s~__REGISTRY__~$(REGISTRY)~g" artifacts/dependencies.txt.template > artifacts/dependencies.txt
> ```

Can we do $(version)-$(GITCOMMIT) to keep it in line with semver and CAPVCD?

**Review by sahithi — APPROVED** [review]
:lgtm: after Arun's comments are addressed on both the PRs

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/193#-:-NWyGcPc-LRdgJp6JYbD:bmqbl6e)* status: all files reviewed, 1 unresolved discussion (waiting on @abaruni, @lzichong, and @rocknes)

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/193)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @abaruni, @arunmk, and @rocknes)

___
*[`Makefile` line 44 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/193#-NWyGILKDfLdjJdztFn3:-NWySHlr0-12gYKpNLTU:b35c0tr) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/a8236db87806eeeaf5c566eecfa29e70971429cf/Makefile#L44)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we do $(version)-$(GITCOMMIT) to keep it in line with semver and CAPVCD?
</blockquote></details>

Updated along with the associated templates, thanks Arun!

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/193#-:-NXOwGQy3v83jRnnybav:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @abaruni and @arunmk)

**Pull request merged**
