### PR TITLE
[VKC-20-cherrypick] fix issue - failed to mount volume to VM (#116)

### PR DESCRIPTION
**Pull request by ymo24**
* add rescanDiskInVM func

Signed-off-by: ymo24 <ymo@vmware.com>

* add nit change

Signed-off-by: ymo24 <ymo@vmware.com>

* add changes

Signed-off-by: ymo24 <ymo@vmware.com>

* add os.writeFIle

Signed-off-by: ymo24 <ymo@vmware.com>

Signed-off-by: ymo24 <ymo@vmware.com>
(cherry picked from commit a279d627c93ffa18f5ee2192fd8a36acdf3f484f)

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/118)

### CODE REVIEW

**Review by lzichong — APPROVED** [review]
:lgtm: after addressing comment

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/118#-:-NI8kzps9Ms_ELaH-7ls:bkbnwf4)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @arunmk and @ymo24)

___
*[`pkg/csi/node.go` line 416 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/118#-NI8kZes4g_oLPdp08LA:-NI8kZetEepMRCde6rxL:bx4tytb) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/dc51f71c2ae3f9483035eaefbf38ee6199307c64/pkg/csi/node.go#L416)):*
> ```Go
> 		if err != nil {
> 			klog.Errorf("Encounter error while walking through the folder: [%v]", err)
> 			return nil
> ```

Should this be returning nil?

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/118)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @arunmk and @lzichong)

___
*[`pkg/csi/node.go` line 416 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/118#-NI8kZes4g_oLPdp08LA:-NI8leom9YqZ1YPyweP3:b-jyke1z) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/dc51f71c2ae3f9483035eaefbf38ee6199307c64/pkg/csi/node.go#L416)):*
<details><summary><i>Previously, lzichong wrote…</i></summary><blockquote>

Should this be returning nil?
</blockquote></details>

 this is like a anonymous function / closure in golang.

**Review by lzichong — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/118)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @arunmk and @ymo24)

___
*[`pkg/csi/node.go` line 416 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/118#-NI8kZes4g_oLPdp08LA:-NI8lkbeD_K8xxm8wukI:bp74iab) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/dc51f71c2ae3f9483035eaefbf38ee6199307c64/pkg/csi/node.go#L416)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

 this is like a anonymous function / closure in golang. 
</blockquote></details>

Gotcha, looks good to me then!

**Review by arunmk — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/118#-:-NI8ryMGAcei0Bn-_992:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ymo24)

**Pull request merged**
