### PR TITLE
[VKC-23][VKC-24] Testing: CSI Test Suite: Basic E2E testing

### PR DESCRIPTION
**Pull request by ymo24**
Automation Test on CSI:

**Storage Profile Quota Limit Testing**
* Add a storage profile using a small limit
* Attempt to create a PV with a large size request
* Verify the error as being a storage limit error

**Dynamic Provisioning Testing**
* Use different reclaim policy (retain and delete)
* Test the use of PV, PVC, Deployment
* Test the RDE update

**Static Provisioning Testing**
* Use different reclaim policy (retain and delete)
*  Test the use of PV, PVC, Deployment

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131)

### CODE REVIEW

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 249 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131)* status: 6 of 250 files reviewed, 11 unresolved discussions (waiting on @arunmk, @lzichong, @rliang88, and @ymo24)

___
*[`tests/e2e/dynamic_provisioning_test.go` line 153 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGbjSbBo4fTNDS1UcS:-NMGbjSbBo4fTNDS1UcT:b-fygusp) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/e2e/dynamic_provisioning_test.go#L153)):*
> ```Go
> 		Expect(err).NotTo(HaveOccurred())
> 		Expect(vcdDisk).NotTo(BeNil())
> 		By("Disk is verified in VCD after PV is deleted")
> ```

please correct me if I am wrong. Shouldn't the disk be deleted too if the PV is deleted in k8s?
___
*[`tests/e2e/dynamic_provisioning_test.go` line 232 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGdezq7JE3Ukx78lda:-NMGdezq7JE3Ukx78ldb:b3m97tk) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/e2e/dynamic_provisioning_test.go#L232)):*
> ```Go
> 
> 	//under delete policy
> 	It("PV resource should get deleted after PV is deleted in kubernetes", func() {
> ```

"PV resource should get deleted after PVC* is deleted in kubernetes"
___
*[`tests/e2e/static_provisioning_test.go` line 59 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGkHsL0clMr2AlSSOO:-NMGkHsM-mGNh-6LRyfa:bw22adj) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/e2e/static_provisioning_test.go#L59)):*
> ```Go
> 		By("Disk is created successfully from VCD")
> 
> 		pv, err = tc.CreatePV(ctx, testDiskName, storageClassDelete, defaultStorageProfile, storageSize, apiv1.PersistentVolumeReclaimDelete)
> ```

Will the cluster RDE also have PV if the PV is statically provisioned? if so, can you please add the check for the RDE as well?
___
*[`tests/e2e/static_provisioning_test.go` line 148 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGkaOk6fO_OBUa0uSA:-NMGkaOk6fO_OBUa0uSB:bke0pky) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/e2e/static_provisioning_test.go#L148)):*
> ```Go
> 		Expect(err).NotTo(HaveOccurred())
> 		By("Disk is created successfully from VCD")
> 		pv, err = tc.CreatePV(ctx, testDiskName, storageClassRetain, defaultStorageProfile, storageSize, apiv1.PersistentVolumeReclaimRetain)
> ```

same comment as before, we might be missing the checks to verify PV in the RDE
___
*[`tests/e2e/static_provisioning_test.go` line 220 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGknxZ-2ntXJKWUWop:-NMGknxZ-2ntXJKWUWoq:b-a1lue1) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/e2e/static_provisioning_test.go#L220)):*
> ```Go
> 		Expect(pv).To(BeNil())
> 
> 		By("Disk is present in VCD")
> ```

Is there any difference between the tests for retain and delete for static provisioning?
___
*[`tests/utils/disk_util.go` line 40 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGtB8o0W4UCAvXDiDH:-NMGtB8o0W4UCAvXDiDI:b-iloyyv) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/utils/disk_util.go#L40)):*
> ```Go
> 	err = ValidateNoAttachedVM(vcdClient, disk)
> 	if err != nil {
> 		return fmt.Errorf("sdsd")
> ```

The error message here should be changed
___
*[`tests/utils/disk_util.go` line 103 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGtUo74gGHPxFc5udI:-NMGtUo74gGHPxFc5udJ:b-6mbd9n) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/utils/disk_util.go#L103)):*
> ```Go
> 	}
> 	if attachedVMs.VmReference != nil && len(attachedVMs.VmReference) > 0 {
> 		return fmt.Errorf("sd")
> ```

a valid error message should be added here as well
___
*[`tests/utils/disk_util.go` line 152 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGtu9z27zUVCqbpnq9:-NMGtu9z27zUVCqbpnqA:b-1oluuc) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/utils/disk_util.go#L152)):*
> ```Go
> 		}
> 	}
> 	//Todo
> ```

Should this Todo be removed?
___
*[`tests/utils/disk_util.go` line 162 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGtyDQAOOuk-5crrMc:-NMGtyDQAOOuk-5crrMd:bc4mz1i) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/utils/disk_util.go#L162)):*
> ```Go
> }
> 
> //Todo: change the name
> ```

This Todo should be removed as well, I believe 
___
*[`tests/utils/disk_util.go` line 186 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGuFDm8LaU_-wM9hRv:-NMGuFDm8LaU_-wM9hRw:b-aquexj) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/utils/disk_util.go#L186)):*
> ```Go
> 		return nil, fmt.Errorf("error occurred while getting vcdClient VDC, [%v]", err)
> 	}
> 	for i := 0; i < vcdsdk.MaxRDEUpdateRetries; i++ {
> ```

The constant used here `vcdsdk.MaxRDEUpdateRetries` mislead me to think that there is some RDE related operation here. Can we create a different constant or use a hardcoded value here?
___
*[`tests/utils/disk_util.go` line 212 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGuY5Z7WtTGwd-h2Qi:-NMGuY5Z7WtTGwd-h2Qj:b-n23i8i) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/utils/disk_util.go#L212)):*
> ```Go
> }
> 
> //
> ```

stray comment line?

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131)* status: 6 of 250 files reviewed, 11 unresolved discussions (waiting on @Anirudh9794, @arunmk, @lzichong, and @rliang88)

___
*[`tests/e2e/dynamic_provisioning_test.go` line 153 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGbjSbBo4fTNDS1UcS:-NMUXOGaC70Yk6B9GfOU:bofkder) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/e2e/dynamic_provisioning_test.go#L153)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

please correct me if I am wrong. Shouldn't the disk be deleted too if the PV is deleted in k8s?
</blockquote></details>

Hi Aniruddha, I tested both "retain" reclaim policy and "delete" policy. For the "retain" policy, disk should be retained while PV is deleted in k8s. For the "delete" policy, disk should be deleted as well if the PV is deleted in k8s.
___
*[`tests/e2e/dynamic_provisioning_test.go` line 232 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGdezq7JE3Ukx78lda:-NMUaBKf8MGgJKhoHSAR:b-g312cy) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/e2e/dynamic_provisioning_test.go#L232)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

"PV resource should get deleted after PVC* is deleted in kubernetes"
</blockquote></details>

Thanks Aniruddha. I already fixed it
___
*[`tests/e2e/static_provisioning_test.go` line 59 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGkHsL0clMr2AlSSOO:-NMUa5eS2O33XNWML3Jk:b-p0oecv) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/e2e/static_provisioning_test.go#L59)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Will the cluster RDE also have PV if the PV is statically provisioned? if so, can you please add the check for the RDE as well?
</blockquote></details>

cluster RDE will not have PV as named-disk is created independently. It is not belong to the cluster. I will add a check which pV is not in RDE as expected.
___
*[`tests/e2e/static_provisioning_test.go` line 220 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGknxZ-2ntXJKWUWop:-NMUYU8ECYTvHgBGamjM:b-r1wzv8) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/e2e/static_provisioning_test.go#L220)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Is there any difference between the tests for retain and delete for static provisioning?
</blockquote></details>

For static provisioning, there is no difference. The named disk will be retained no matter reclaim policy is "retained" or "deleted". I can mention it in comment. Thanks Aniruddha!



_Code quote (from tests/e2e/dynamic_provisioning_test.go):_
```Go
scenario 2: use 'Delete' retention policy. step2: install a deployment using the above PVC.
```
___
*[`tests/utils/disk_util.go` line 40 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGtB8o0W4UCAvXDiDH:-NMUavIkDOqZsEQH5xoi:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/utils/disk_util.go#L40)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

The error message here should be changed
</blockquote></details>

Done.
___
*[`tests/utils/disk_util.go` line 103 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGtUo74gGHPxFc5udI:-NMU_q2rDrR8iZ4MSr3z:bfufdf4) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/utils/disk_util.go#L103)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

a valid error message should be added here as well
</blockquote></details>

Sorry I forgot to check this file. Thanks for the reminder.
___
*[`tests/utils/disk_util.go` line 152 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGtu9z27zUVCqbpnq9:-NMU_uF2AqTn9LVlB-HX:bfufdf4) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/utils/disk_util.go#L152)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Should this Todo be removed?
</blockquote></details>

Sorry I forgot to check this file. Thanks for the reminder.
___
*[`tests/utils/disk_util.go` line 162 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGtyDQAOOuk-5crrMc:-NMU_ucM9F6Y6TBhjzYp:bfufdf4) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/utils/disk_util.go#L162)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

This Todo should be removed as well, I believe 
</blockquote></details>

Sorry I forgot to check this file. Thanks for the reminder.
___
*[`tests/utils/disk_util.go` line 186 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGuFDm8LaU_-wM9hRv:-NMUa3WM7fX3gfffz0yE:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/utils/disk_util.go#L186)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

The constant used here `vcdsdk.MaxRDEUpdateRetries` mislead me to think that there is some RDE related operation here. Can we create a different constant or use a hardcoded value here?
</blockquote></details>

Done.
___
*[`tests/utils/disk_util.go` line 212 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGuY5Z7WtTGwd-h2Qi:-NMU_z68Dw_u7IxqwIT-:b-60jtt2) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/utils/disk_util.go#L212)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

stray comment line?
</blockquote></details>

Sorry I forgot to check this file. Thanks for the reminder.

**Review by arunmk — APPROVED** [review]
:lgtm: with a few small changes

> Reviewed 3 of 249 files at r1, 2 of 5 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-:-NMVfDf04Zmnm4xXAPfE:b-uouea0)* status: 8 of 250 files reviewed, 14 unresolved discussions (waiting on @Anirudh9794, @lzichong, @rliang88, and @ymo24)

___
*[`tests/e2e/dynamic_provisioning_test.go` line 153 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGbjSbBo4fTNDS1UcS:-NMVd97QD9cjOLLT8A_W:b-8fx2u7) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/e2e/dynamic_provisioning_test.go#L153)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

Hi Aniruddha, I tested both "retain" reclaim policy and "delete" policy. For the "retain" policy, disk should be retained while PV is deleted in k8s. For the "delete" policy, disk should be deleted as well if the PV is deleted in k8s.
</blockquote></details>

:+1: 
___
*[`tests/e2e/dynamic_provisioning_test.go` line 176 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMVe2lQ4zg1Xg7_eEDN:-NMVe2lQ4zg1Xg7_eEDO:bx6gxes) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/79e8beb6da5bb5bef323b17625dd44657722b487/tests/e2e/dynamic_provisioning_test.go#L176)):*
> ```Go
> 		By(fmt.Sprintf("Disk [%s] is deleted successfully in VCD", dynamicPVName))
> 
> 		err = utils.RemoveDiskViaRDE(tc.VcdClient, dynamicPVName, tc.ClusterId)
> ```

In the case where the disk is because of a `retain, I think `DeleteDisk` should make CSI remove the entry from RDE. So we should just wait for PV deleted and then check if the entry is removed from RDE.
Is this not the case?
___
*[`tests/e2e/dynamic_provisioning_test.go` line 213 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMVdGUJ1y6CZk1jCUYT:-NMVdGUK8QaISQ03SGrr:b-7ilvhb) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/79e8beb6da5bb5bef323b17625dd44657722b487/tests/e2e/dynamic_provisioning_test.go#L213)):*
> ```Go
> 		Expect(pv).NotTo(BeNil())
> 
> 		By("PV shoule be presented in VCD")
> ```

typo
___
*[`tests/e2e/static_provisioning_test.go` line 59 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMGkHsL0clMr2AlSSOO:-NMVed1cA-qM_9t35Hv0:b-8fx2u7) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/93f5322ca0847410495fa6d6d1acbdc9bb6d9c46/tests/e2e/static_provisioning_test.go#L59)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

cluster RDE will not have PV as named-disk is created independently. It is not belong to the cluster. I will add a check which pV is not in RDE as expected.
</blockquote></details>

:+1: 
___
*[`tests/utils/k8s_client_util.go` line 10 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-NMVf6Li6vJsDXd-8xWE:-NMVf6Li6vJsDXd-8xWF:b-pis99q) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/79e8beb6da5bb5bef323b17625dd44657722b487/tests/utils/k8s_client_util.go#L10)):*
> ```Go
> )
> 
> func WaitForPVDeleted(ctx context.Context, pvName string, tc *testingsdk.TestClient) error {
> ```

Should this go to common core?

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/131#-:-NMWlVvI0DPqewUrIouN:bg7igkv)* status: 8 of 250 files reviewed, 14 unresolved discussions (waiting on @lzichong, @rliang88, and @ymo24)

**Pull request merged**
