### PR TITLE
Fix typos and add some hints

### PR DESCRIPTION
**Pull request by mate201**
## Description

This PR fixes various typos across manifests and samples. It introduces a few hints as well. 

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/167)

### CODE REVIEW

**Review by ymo24 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/167)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @mate201)

___
*[`manifests/vcloud-csi-config.yaml` line 8 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/167#-NTpvYWU2sAnlPvG23uz:-NTpvYWU2sAnlPvG23v-:b-srle19) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/660361dc6e2c368f725099aa376b280b04b911ce/manifests/vcloud-csi-config.yaml#L8)):*
> ```YAML
>   namespace: kube-system
> data:
>   vcloud-csi-config.yaml: |+
> ```

Is there reason to remove the Block Chomping Indicator?
___
*[`samples/my-pvc-ext4.yaml` line 24 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/167#-NTpvQXqDbjcg_CwrzzN:-NTpvQXqDbjcg_CwrzzO:bff4l47) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/660361dc6e2c368f725099aa376b280b04b911ce/samples/my-pvc-ext4.yaml#L24)):*
> ```YAML
> reclaimPolicy: Delete
> parameters:
>   storageProfile: "dev"
> ```

Please keep the storageProfile

**Comment by mate201** [comment]
Hi there!

From my understanding, it was used to add a new line character at the end of a Yaml file mounted. The problem is that k8s ignores it. To add a new line, one would need to add `+` to `|` **and a new line** right after `clusterid`. Though, in general, it's not needed as everyone ignores that new line at the end of a Yaml file requirement.

> Please keep the storageProfile

Can you please elaborate on this more? Is it needed for production usage? What should be set for production in case it's not required?

**Review by Anirudh9794 — APPROVED** [review]

**Comment by ymo24** [comment]
> Hi there!
> 
> From my understanding, it was used to add a new line character at the end of a Yaml file mounted. The problem is that k8s ignores it. To add a new line, one would need to use `|+` **and a new line** right after `clusterid`. Though, in general, it's not needed as everyone ignores that new line at the end of a Yaml file requirement.
> 
> In case you have a different experience, and it works in your environment, I can return it.

Thank you. I have approved your PR.

**Review by ymo24 — APPROVED** [review]
> Reviewed 10 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/167)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @mate201)

**Review by sahithi — APPROVED** [review]

**Review by mate201 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/167)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @ymo24)

___
*[`manifests/vcloud-csi-config.yaml` line 8 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/167#-NTpvYWU2sAnlPvG23uz:-NUrZDTl3VgUQhcwN-IG:bl40ino) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/660361dc6e2c368f725099aa376b280b04b911ce/manifests/vcloud-csi-config.yaml#L8)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

Is there reason to remove the Block Chomping Indicator?
</blockquote></details>

Discussed.
___
*[`samples/my-pvc-ext4.yaml` line 24 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/167#-NTpvQXqDbjcg_CwrzzN:-NUrZ2SK4EPQLW2uRd_t:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/660361dc6e2c368f725099aa376b280b04b911ce/samples/my-pvc-ext4.yaml#L24)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

Please keep the storageProfile
</blockquote></details>

Done.

**Comment by mate201** [comment]
Sorry, I don't know much about this reviewable tool, but at the moment, the merge button is blocked for me.

@ymo24  I think you should unblock this merge

**Comment by ymo24** [comment]
> 

Hey @mate201,  we have merged your PR. 

Best,
Yan

**Pull request merged**
