### PR TITLE
[VKC-55] Package and push CSI CRS airgap manifests when image is being built

### PR DESCRIPTION
**Pull request by lzichong**
Signed-off-by: lzichong <lzichong@vmware.com>

* Testings:
  * ran `make dev` which gave `__REGISTRY__/cloud-director-named-disk-csi-driver:version.gitSha`
  * ran `make prod` which updated the `image: __REGISTRY__/cloud-provider-for-cloud-director:version`
    * ex) `image: __REGISTRY__/cloud-director-named-disk-csi-driver:lzichong-v1.3.0` (`lzichong-v1.3.0` is replaced by `release/version`)
  * Verified the container in TKG VM by extracting the container, and found 3 expected manifest files
  * 1. csi-node-crs-airgap.yaml
  * 2. csi-driver-airgap.yaml
  * 3. csi-controller-crs-airgap.yaml
To pull CRS dev container: `pull __REGISTRY__/csi-crs-airgapped:e806be2`
To pull CRS prod container: `pull __REGISTRY__/csi-crs-airgapped:lzichong-v1.3.0` (these are all just testing containers, they will be updated once official manifest/versions are used as packaging)

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/136)

### CODE REVIEW

**Review by sakthisunda — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @abaruni, @arunmk, and @rocknes)

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/136)* status: all files reviewed, 1 unresolved discussion (waiting on @abaruni, @arunmk, and @lzichong)

___
*[`artifacts/Dockerfile` line 2 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/136#-NN8le0f3bXNLKffLb6r:-NN8le0gAw7FYxsKDn5W:b8g0fnl) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/5aa6414462f61ff90333423d083a09b935171a99/artifacts/Dockerfile#L2)):*
> ```Dockerfile
> FROM scratch
> COPY /artifacts/*.yaml /src/artifact/
> ```

Umm.. the templates won't be missed?

We need to ship the templates, since the substitution of __REGISTRY__ will be done by CSE while deploying the ephemeral VM.

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/136)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @abaruni, @arunmk, @rocknes, and @sakthisunda)

___
*[`artifacts/Dockerfile` line 2 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/136#-NN8le0f3bXNLKffLb6r:-NN91qT45qRvSpxeY5lJ:b-h2ws3i) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/5aa6414462f61ff90333423d083a09b935171a99/artifacts/Dockerfile#L2)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Umm.. the templates won't be missed?

We need to ship the templates, since the substitution of __REGISTRY__ will be done by CSE while deploying the ephemeral VM.
</blockquote></details>

Updated as discussed over Slack, artifacts will be using `.template` file type as there will be substitution in the template files. gitSha/version is plugged in, leaving just `__REGISTRY__` to be substituted. Thanks Aritra!

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/136#-:-NN96meB-Ss6HBNXG5Oz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @abaruni, @arunmk, and @rocknes)

**Review by rocknes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @abaruni and @arunmk)

**Review by abaruni — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arunmk)

**Pull request merged**
