### PR TITLE
[VCDA-2878 & VCDA-2937] using api 36.0 and added etag tests

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy7 <66969084+ltimothy7@users.noreply.github.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/6)

### CODE REVIEW

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/6)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @arunmk)

___
*[pkg/vcdclient/disks_system_test.go, line 111 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/6#-MkA428a-tiskulqJmBV:-MkAGQpd-1p8X3sMOB1w:b-ucfknh) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/a33907d916e2592ba3c8d690d57922021af3e62c/pkg/vcdclient/disks_system_test.go#L111)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

good test!
</blockquote></details>

Thanks!
___
*[pkg/vcdswaggerclient/api_defined_entity.go, line 607 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/6#-MkA4exw34M4dMMgFDtb:-MkAGS21DGVyE52OjpfJ:bgfnrcd) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/a33907d916e2592ba3c8d690d57922021af3e62c/pkg/vcdswaggerclient/api_defined_entity.go#L607)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

hmm...I don't follow this change...is the etag coming from somewhere else?
</blockquote></details>

The empty string is being returned in case of an error; at this point, no etag was extracted from the response header
___
*[pkg/config/cloudconfig_test.go, line 31 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/6#-Mk9eHNrCQYUE_tWn5P6:-MkAGZ508QHw7p6g3Ik-:b-3b85t4) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/a33907d916e2592ba3c8d690d57922021af3e62c/pkg/config/cloudconfig_test.go#L31)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This does not need to be here :)
</blockquote></details>

Done. Thanks for the catch :)

**Review by Anirudh9794 — COMMENTED** [review]
:lgtm: Minor comments

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/6#-:-MkDe35s4CuElaFe0sNZ:by0nmtq)* status: all files reviewed, 8 unresolved discussions (waiting on @arunmk and @ltimothy7)

___
*[pkg/vcdclient/client.go, line 39 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/6#-MkDHAtN2qYIXYZgvnmI:-MkDHAtN2qYIXYZgvnmJ:bxf5tb6) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d361d8f5cd360f1b97810fb4cfd256991ff716aa/pkg/vcdclient/client.go#L39)):*
> ```Go
> 	} else if r != nil && r.StatusCode == 401 {
> 		klog.Info("Refreshing tokens as previous one has expired")
> 		client.vcdClient.Client.APIVersion = VCloudApiVersion
> ```

Is the variable `VCloudApiVersion` declared somewhere in the code?
___
*[pkg/vcdclient/disks_system_test.go, line 137 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/6#-MkDZdfy1GPEBh28eLY0:-MkDZdfy1GPEBh28eLY1:b-a56821) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d361d8f5cd360f1b97810fb4cfd256991ff716aa/pkg/vcdclient/disks_system_test.go#L137)):*
> ```Go
> 	rdePvs3, _, _, err := vcdClient.GetRDEPersistentVolumes()
> 	assert.NoError(t, err, "unable to get RDE PVs")
> 	assert.Equal(t, true, foundStringInSlice(addPv1, rdePvs3), "pv [%s] should be found in rde pvs", addPv1)
> ```

assert.True() can be used instead
https://pkg.go.dev/github.com/stretchr/testify/assert
___
*[pkg/vcdclient/disks_system_test.go, line 146 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/6#-MkD_6aJ3JL1aOc7rc7J:-MkD_6aJ3JL1aOc7rc7K:bvu24td) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d361d8f5cd360f1b97810fb4cfd256991ff716aa/pkg/vcdclient/disks_system_test.go#L146)):*
> ```Go
> 	rdePvs3, etag3, defEnt3, err := vcdClient.GetRDEPersistentVolumes()
> 	assert.NoError(t, err, "unable to get RDE PVs")
> 	assert.Equal(t, false, foundStringInSlice(addPv2, rdePvs3), "pv [%s] should not be in rde pvs", addPv2)
> ```

assert.False()
___
*[pkg/vcdclient/disks_system_test.go, line 150 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/6#-MkD_Nn36DE22TmbKHp1:-MkD_Nn36DE22TmbKHp2:b-q5nay4) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d361d8f5cd360f1b97810fb4cfd256991ff716aa/pkg/vcdclient/disks_system_test.go#L150)):*
> ```Go
> 	// try updating RDE PVs with current etag
> 	updatedRdePvs3 := append(rdePvs3, addPv2)
> 	httpResponse3, err := vcdClient.updateRDEPersistentVolumes(updatedRdePvs3, etag3, defEnt3)
> ```

Just a question for my own curiosity. Will etag change after a failed update attempt?
___
*[pkg/vcdswaggerclient/api_defined_entity.go, line 720 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/6#-MkDdQJ7DWZREm9nnuFs:-MkDdQJ7DWZREm9nnuFt:b-fzwrzk) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d361d8f5cd360f1b97810fb4cfd256991ff716aa/pkg/vcdswaggerclient/api_defined_entity.go#L720)):*
> ```
> &#39;true&#39;
> ```
Should this be just "true"?

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/6)* status: 11 of 13 files reviewed, 8 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[pkg/vcdclient/client.go, line 39 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/6#-MkDHAtN2qYIXYZgvnmI:-MkIcHQC33eFWFrfc4Wu:b-jov37a) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d361d8f5cd360f1b97810fb4cfd256991ff716aa/pkg/vcdclient/client.go#L39)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Is the variable `VCloudApiVersion` declared somewhere in the code?
</blockquote></details>

Yes, it is in auth.go
___
*[pkg/vcdclient/disks_system_test.go, line 137 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/6#-MkDZdfy1GPEBh28eLY0:-MkIcL8_ExAQGDt7EqFJ:bwaghig) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d361d8f5cd360f1b97810fb4cfd256991ff716aa/pkg/vcdclient/disks_system_test.go#L137)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

assert.True() can be used instead
https://pkg.go.dev/github.com/stretchr/testify/assert
</blockquote></details>

Done. Thank you Aniruddha
___
*[pkg/vcdclient/disks_system_test.go, line 146 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/6#-MkD_6aJ3JL1aOc7rc7J:-MkIcOC0BIg72Ws2OvLG:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d361d8f5cd360f1b97810fb4cfd256991ff716aa/pkg/vcdclient/disks_system_test.go#L146)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

assert.False()
</blockquote></details>

Done.
___
*[pkg/vcdclient/disks_system_test.go, line 150 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/6#-MkD_Nn36DE22TmbKHp1:-MkIcoQq2SsWK7ex8HKt:b-nuroyh) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d361d8f5cd360f1b97810fb4cfd256991ff716aa/pkg/vcdclient/disks_system_test.go#L150)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Just a question for my own curiosity. Will etag change after a failed update attempt?
</blockquote></details>

It will not; the etag will only change after a successful update; it is more like a revision number
___
*[pkg/vcdswaggerclient/api_defined_entity.go, line 720 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/6#-MkDdQJ7DWZREm9nnuFs:-MkId6pG-lrfJb36ioYC:b-wc02eb) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d361d8f5cd360f1b97810fb4cfd256991ff716aa/pkg/vcdswaggerclient/api_defined_entity.go#L720)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

> ```
> &#39;true&#39;
> ```
Should this be just "true"?
</blockquote></details>

Done.yes, thanks

**Review by arunmk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/6)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794)

**Pull request merged**
