### PR TITLE
[VCDA-6929] Remove references of registry from Makefile

### PR DESCRIPTION
**Pull request by lzichong**
## Description
Please provide a brief description of the changes proposed in this Pull Request

- Remove references of `$(REGISTRY)` from Makefile
- Use projects-stg as the hardcoded value for pushing images (including sig store components)
  - This is because in the CI yaml file we will pull and tag, so it is ok to hardcode here

## Checklist
- [ ] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## Testing Done
Please provide a screenshot of the testing results for the code change in this Pull Request. Verify that this pull request's code change will not affect CSI's normal operation

## Issue
If applicable, please reference the relevant issue

Fixes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/254)

### CODE REVIEW

**Review by abaruni — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/254)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rocknes)

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/254)* status: all files reviewed, 1 unresolved discussion (waiting on @lzichong)

___
*[`Makefile` line 114 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/254#-NoYnzzN6IAv8-UPsBUb:-NoYnzzN6IAv8-UPsBUc:bme8hoe) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/9dc1ecc1cc6e1cbec1e826478bcf7e5e00802458/Makefile#L114)):*
> ```Makefile
> 		--platform $(PLATFORM) \
> 		--file Dockerfile \
> 		--tag $(CSI_IMG):$(VERSION) \
> ```

can we tag with projects-stg here directly? Then we don't need to tag it again in docker-push-csi and docker-push-artifacts

Multiple tagging can cause issues when we call one of these targets from another target

**Review by rocknes — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/254)* status: all files reviewed, 1 unresolved discussion (waiting on @lzichong)

**Review by lzichong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/254)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

___
*[`Makefile` line 114 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/254#-NoYnzzN6IAv8-UPsBUb:-NoYoocaD68PMEtHvSz4:b-a1rly) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/9dc1ecc1cc6e1cbec1e826478bcf7e5e00802458/Makefile#L114)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

can we tag with projects-stg here directly? Then we don't need to tag it again in docker-push-csi and docker-push-artifacts

Multiple tagging can cause issues when we call one of these targets from another target
</blockquote></details>

In the future the pipelines will make use of this make target so we don't associate the tagging to a particular registry at this make target, we are also not calling targets within other targets (so no duplicate nested target calls)

**Pull request merged**
