### PR TITLE
[VKC-20] fix issue - failed to mount volume to VM

### PR DESCRIPTION
**Pull request by ymo24**
* add rescanDiskInVM func() into CSI
* Test SCSI bus rescan is performed successfully inside the VM.

Signed-off-by: ymo24 <ymo@vmware.com>

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116)

### CODE REVIEW

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116)* status: all files reviewed, 3 unresolved discussions (waiting on @arunmk and @ymo24)

___
*[`pkg/csi/node.go` line 127 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116#-NHzUmkJ0GhB81AoN_i4:-NHzUmkJ0GhB81AoN_i5:b2je9tg) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/9adec1067cf1006f7b6e90df608563d32f10b36a/pkg/csi/node.go#L127)):*
> ```Go
> 	err := ns.rescanDiskInVM(ctx)
> 	if err != nil {
> 		return nil, status.Errorf(codes.Internal, "unable to scan SCSI bus for vm [%s]: [%v}", vmFullName, err)
> ```

"}" bracket should be changed to "]"
___
*[`pkg/csi/node.go` line 411 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116#-NHzgmAR1QIfqlMgf8c6:-NHzgmAS2sjFQYSSjwyw:b-h2gcbe) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/9adec1067cf1006f7b6e90df608563d32f10b36a/pkg/csi/node.go#L411)):*
> ```Go
> // where "- - -" represent controller channel lun.
> func (ns *nodeService) rescanDiskInVM(ctx context.Context) error {
> 	err := filepath.Walk(ScsiHostPath, func(path string, fi os.FileInfo, err error) error {
> ```

Comment about what the unnamed function argument within `Walk` is doing would be helpful.
___
*[`pkg/csi/node.go` line 413 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116#-NHzgt7NCxOj6H4mwqhx:-NHzgt7NCxOj6H4mwqhy:beraapg) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/9adec1067cf1006f7b6e90df608563d32f10b36a/pkg/csi/node.go#L413)):*
> ```Go
> 	err := filepath.Walk(ScsiHostPath, func(path string, fi os.FileInfo, err error) error {
> 		if err != nil {
> 			return nil
> ```

nil is returned if err is not nil. Is this as expected?

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[`pkg/csi/node.go` line 127 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116#-NHzUmkJ0GhB81AoN_i4:-NHzqpwcDJ3L9N3k3WsU:bzg28w6) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/9adec1067cf1006f7b6e90df608563d32f10b36a/pkg/csi/node.go#L127)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

"}" bracket should be changed to "]"
</blockquote></details>

Thanks Aniruddha
___
*[`pkg/csi/node.go` line 411 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116#-NHzgmAR1QIfqlMgf8c6:-NHzneY04xxTKhcUXDrJ:b-61j7bx) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/9adec1067cf1006f7b6e90df608563d32f10b36a/pkg/csi/node.go#L411)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Comment about what the unnamed function argument within `Walk` is doing would be helpful.
</blockquote></details>

I have added the description. Thanks a lot!
___
*[`pkg/csi/node.go` line 413 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116#-NHzgt7NCxOj6H4mwqhx:-NHzqiWaB6pZbE9Cz0zE:bwr0rvy) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/9adec1067cf1006f7b6e90df608563d32f10b36a/pkg/csi/node.go#L413)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

nil is returned if err is not nil. Is this as expected?
</blockquote></details>

We need to return nil to ensure walk through  can continue, which means we should visit all the files under the current folder.. Please take a look at https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/main/pkg/csi/node.go#L415

**Review by Anirudh9794 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116#-:-NI-2Mc-0UovqV3TLoUL:bnfp4nl)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @arunmk and @ymo24)

___
*[`pkg/csi/node.go` line 413 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116#-NHzgt7NCxOj6H4mwqhx:-NI-2HLAApogP38N5zN2:bvs55d0) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/9adec1067cf1006f7b6e90df608563d32f10b36a/pkg/csi/node.go#L413)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

We need to return nil to ensure walk through  can continue, which means we should visit all the files under the current folder.. Please take a look at https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/main/pkg/csi/node.go#L415
</blockquote></details>

Thank you

**Review by arunmk — CHANGES_REQUESTED** [review]
Only one main concern regarding the bash execution. Rest look good.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116#-:-NI54dCe0NFRrvqytp3g:b-tf0fv0)* status: all files reviewed, 6 unresolved discussions (waiting on @Anirudh9794 and @ymo24)

___
*[`pkg/csi/node.go` line 413 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116#-NHzgt7NCxOj6H4mwqhx:-NI53TNE325vscZ-TeKu:bsihe96) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/9adec1067cf1006f7b6e90df608563d32f10b36a/pkg/csi/node.go#L413)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Thank you
</blockquote></details>

yes, this is like a anonymous function / closure in golang.
___
*[`pkg/csi/node.go` line 33 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116#-NI54VbN8Wdzckw_7evQ:-NI54VbO9Zk0uWIylTZv:b7akh07) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/c006ebb251d8c00bb4f33c522d9b9e2de4e5658c/pkg/csi/node.go#L33)):*
> ```Go
> 	DevDiskPath          = "/dev/disk/by-path"
> 	ScsiHostPath         = "/sys/class/scsi_host"
> 	HostNameRegexPattern = "^host[0-9]"
> ```

is it from host0-host9 alone? no double digits?
___
*[`pkg/csi/node.go` line 427 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116#-NI5432z106UDLGJd1Ne:-NI5432z106UDLGJd1Nf:bbqeerl) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/c006ebb251d8c00bb4f33c522d9b9e2de4e5658c/pkg/csi/node.go#L427)):*
> ```Go
> 		}
> 		if reg.MatchString(fi.Name()) {
> 			_, executedErr := exec.Command("bash", "-c", fmt.Sprintf("echo \"- - -\" > %s/scan", path)).CombinedOutput()
> ```

Can we use `os.WriteFile` rather than a bash command? Ensure that the overwrite happens.
___
*[`pkg/csi/node.go` line 429 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116#-NI54ISMEpHjqqds39JS:-NI54ISMEpHjqqds39JT:bxwjmt8) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/c006ebb251d8c00bb4f33c522d9b9e2de4e5658c/pkg/csi/node.go#L429)):*
> ```Go
> 			_, executedErr := exec.Command("bash", "-c", fmt.Sprintf("echo \"- - -\" > %s/scan", path)).CombinedOutput()
> 			if executedErr != nil {
> 				klog.Errorf("Encounter error while rescanning the disk in VM;executing command failed, [%v]", executedErr)
> ```

vmFullName is helpful here as well

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[`pkg/csi/node.go` line 427 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116#-NI5432z106UDLGJd1Ne:-NI6VeoNCAbaOwcYL87x:b7ydr7a) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/c006ebb251d8c00bb4f33c522d9b9e2de4e5658c/pkg/csi/node.go#L427)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we use `os.WriteFile` rather than a bash command? Ensure that the overwrite happens.
</blockquote></details>

Already pushed the change. Thanks Arun
___
*[`pkg/csi/node.go` line 429 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116#-NI54ISMEpHjqqds39JS:-NI6Ush9Bmbk1W0fxuGg:bwljjp1) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/c006ebb251d8c00bb4f33c522d9b9e2de4e5658c/pkg/csi/node.go#L429)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

vmFullName is helpful here as well
</blockquote></details>

Already pushed the changes. Thanks Arun

**Review by ymo24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[`pkg/csi/node.go` line 33 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116#-NI54VbN8Wdzckw_7evQ:-NI8VEHQ1xYloIa8zxWG:bkwbe8o) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/c006ebb251d8c00bb4f33c522d9b9e2de4e5658c/pkg/csi/node.go#L33)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

is it from host0-host9 alone? no double digits?
</blockquote></details>

I used "^host[0-9]+" instead of "^host[0-9]". It can present double digits as well.

**Review by arunmk — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/116#-:-NI8XeB01PbrswaXasol:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)

**Pull request merged**
