### PR TITLE
[VCDA-2527] Consume machine user tokens in CSI

### PR DESCRIPTION
**Pull request by Anirudh9794**
Create function to get access token from refresh token
Create function to check if the user is a system administrator
Use Access token to create vcd client

Testing done:
* Created a cluster with CPI running using the refresh token supplied from CSE

@arunmk @ltimothy7

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/5)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/5)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[pkg/vcdclient/auth.go, line 52 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/5#-MjoZMzDEtnSN7dvGyKF:-MjoZMzDEtnSN7dvGyKG:b-k04hzi) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/18fa08c1de1bd7631489cbe7138e45720798ab68/pkg/vcdclient/auth.go#L52)):*
> ```Go
> 	var resp *http.Response
> 	if config.RefreshToken != "" {
> 		// Since it is not known if the user is sysadmin, try to get the access token using tenanted endpoint
> ```

Should there be a different endpoint based on the isSysAdmin check below, or can the tenanted endpoint be used for tenanted and sysadmin users?
___
*[pkg/vcdclient/auth.go, line 207 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/5#-MjoZjaD640NRRbTHtWa:-MjoZjaD640NRRbTHtWb:bydhe8r) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/18fa08c1de1bd7631489cbe7138e45720798ab68/pkg/vcdclient/auth.go#L207)):*
> ```Go
> 	isSysAdmin := output.Roles[0] == "System Administrator"
> 	return isSysAdmin, nil
> }
> ```

nit: newline needed

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/5)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[pkg/vcdclient/auth.go, line 52 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/5#-MjoZMzDEtnSN7dvGyKF:-Mjp5A_j2Vj1oy7Vg-jb:bsmb6yt) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/18fa08c1de1bd7631489cbe7138e45720798ab68/pkg/vcdclient/auth.go#L52)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Should there be a different endpoint based on the isSysAdmin check below, or can the tenanted endpoint be used for tenanted and sysadmin users?
</blockquote></details>

It is possible for sysadmin to get access token using tenanted url. The other way is not true.
I have tried to use the sysadmin access token obtained from tenanted url in other admin operations and it succeeded.
I will confirm in the tokens channel if this is an expected behavior

**Comment by Anirudh9794** [comment]
___
*[pkg/vcdclient/auth.go, line 207 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/5#-MjoZjaD640NRRbTHtWa:-Mk2sE1q4xSZMeMgUhJn:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/18fa08c1de1bd7631489cbe7138e45720798ab68/pkg/vcdclient/auth.go#L207)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

nit: newline needed
</blockquote></details>

Done.

**Review by arunmk — APPROVED** [review]
:lgtm: the same comments for CPI hold

> Reviewed 4 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/5#-:-MkIfwi3-pj_b7JGj7KA:bnqcf0q)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

**Pull request merged**
